import { createConnection } from 'mysql2/promise';

const conn = await createConnection(process.env.DATABASE_URL);

// Limpiar módulos existentes
await conn.query('DELETE FROM course_modules');

const modules = [
  // ─── INGLÉS BÁSICO (id=1) ─────────────────────────────────────────────────
  { courseId: 1, sortOrder: 1, title: 'El Alfabeto y Pronunciación', description: 'Aprende las 26 letras del alfabeto inglés y su pronunciación correcta.', content: '## El Alfabeto Inglés\n\nEl alfabeto inglés tiene 26 letras. La pronunciación es diferente al español en muchos casos.\n\n**Vocales:** A (ei), E (ii), I (ai), O (ou), U (iu)\n\n**Consonantes importantes:**\n- B (bi), C (si), D (di), F (ef), G (yi)\n- H (eich), J (yei), K (kei), L (el), M (em)\n- N (en), P (pi), Q (kiu), R (ar), S (es)\n- T (ti), V (vi), W (dobliu), X (ex), Y (uai), Z (zi)\n\n### Ejercicio\nPractica deletreando tu nombre en inglés.', externalUrl: 'https://www.youtube.com/watch?v=UMGxgHFSYkU' },
  { courseId: 1, sortOrder: 2, title: 'Saludos y Presentaciones', description: 'Aprende a saludar y presentarte en inglés en situaciones cotidianas.', content: '## Saludos Básicos\n\n| Inglés | Español |\n|--------|--------|\n| Hello / Hi | Hola |\n| Good morning | Buenos días |\n| Good afternoon | Buenas tardes |\n| Good evening | Buenas noches |\n| Goodbye / Bye | Adiós |\n\n## Presentaciones\n\n- **My name is...** = Mi nombre es...\n- **I am from...** = Soy de...\n- **Nice to meet you** = Mucho gusto\n- **How are you?** = ¿Cómo estás?\n- **I am fine, thank you** = Estoy bien, gracias\n\n### Diálogo de práctica\n\n> A: Hello! My name is Carlos. What is your name?\n> B: Hi Carlos! My name is Ana. Nice to meet you!\n> A: Nice to meet you too! How are you?\n> B: I am fine, thank you. And you?\n> A: I am great!', externalUrl: 'https://www.youtube.com/watch?v=4_ItHSbNEBE' },
  { courseId: 1, sortOrder: 3, title: 'Números y Colores', description: 'Aprende los números del 1 al 100 y los colores principales en inglés.', content: '## Números en Inglés\n\n**Del 1 al 20:**\n1=one, 2=two, 3=three, 4=four, 5=five, 6=six, 7=seven, 8=eight, 9=nine, 10=ten\n11=eleven, 12=twelve, 13=thirteen, 14=fourteen, 15=fifteen\n16=sixteen, 17=seventeen, 18=eighteen, 19=nineteen, 20=twenty\n\n**Decenas:**\n30=thirty, 40=forty, 50=fifty, 60=sixty, 70=seventy, 80=eighty, 90=ninety, 100=one hundred\n\n## Colores\n\n| Inglés | Español |\n|--------|--------|\n| Red | Rojo |\n| Blue | Azul |\n| Green | Verde |\n| Yellow | Amarillo |\n| White | Blanco |\n| Black | Negro |\n| Orange | Naranja |\n| Purple | Morado |\n| Pink | Rosa |\n| Brown | Café/Marrón |', externalUrl: 'https://www.youtube.com/watch?v=ybNH1a14vQY' },
  { courseId: 1, sortOrder: 4, title: 'Vocabulario del Trabajo', description: 'Palabras y frases esenciales para el entorno laboral en inglés.', content: '## Vocabulario Laboral Básico\n\n**Lugares de trabajo:**\n- Office = Oficina\n- Meeting room = Sala de juntas\n- Reception = Recepción\n- Warehouse = Almacén\n\n**Personas:**\n- Boss / Manager = Jefe / Gerente\n- Employee = Empleado\n- Client / Customer = Cliente\n- Colleague = Colega\n\n**Acciones comunes:**\n- To work = Trabajar\n- To call = Llamar\n- To send an email = Enviar un correo\n- To schedule a meeting = Agendar una reunión\n- To sign a document = Firmar un documento\n\n**Frases útiles:**\n- "Can I help you?" = ¿Puedo ayudarle?\n- "Please hold" = Por favor espere\n- "I will transfer your call" = Le transferiré la llamada\n- "The meeting is at 3 PM" = La reunión es a las 3 PM', externalUrl: 'https://www.youtube.com/watch?v=7Xr9BNmFOyg' },

  // ─── INGLÉS INTERMEDIO (id=2) ─────────────────────────────────────────────
  { courseId: 2, sortOrder: 1, title: 'Tiempos Verbales: Presente y Pasado', description: 'Domina el presente simple, presente continuo y pasado simple en inglés.', content: '## Presente Simple\n\nUso: hábitos, hechos, rutinas.\n\n**Estructura:** Subject + Verb (base form)\n- I work every day. = Trabajo todos los días.\n- She works at 9 AM. = Ella trabaja a las 9 AM.\n\n## Presente Continuo\n\nUso: acciones que ocurren ahora mismo.\n\n**Estructura:** Subject + am/is/are + Verb-ing\n- I am working now. = Estoy trabajando ahora.\n- They are having a meeting. = Están teniendo una reunión.\n\n## Pasado Simple\n\nUso: acciones completadas en el pasado.\n\n**Estructura:** Subject + Verb (past form)\n- I worked yesterday. = Trabajé ayer.\n- She called the client. = Ella llamó al cliente.\n\n**Verbos irregulares comunes:**\n- go → went, come → came, have → had\n- make → made, take → took, give → gave', externalUrl: 'https://www.youtube.com/watch?v=Rjj6UKbsHk4' },
  { courseId: 2, sortOrder: 2, title: 'Conversaciones de Negocios', description: 'Aprende a comunicarte profesionalmente en reuniones, llamadas y correos.', content: '## En Reuniones de Negocios\n\n**Para empezar una reunión:**\n- "Let\'s get started." = Empecemos.\n- "The purpose of this meeting is..." = El propósito de esta reunión es...\n\n**Para dar tu opinión:**\n- "In my opinion..." = En mi opinión...\n- "I think that..." = Creo que...\n- "I agree / I disagree" = Estoy de acuerdo / No estoy de acuerdo\n\n**En llamadas telefónicas:**\n- "This is [name] calling from [company]." = Le habla [nombre] de [empresa].\n- "May I speak with...?" = ¿Podría hablar con...?\n- "Could you please repeat that?" = ¿Podría repetir eso?\n\n**En correos electrónicos:**\n- "I am writing to inform you..." = Le escribo para informarle...\n- "Please find attached..." = Adjunto encontrará...\n- "Looking forward to hearing from you." = Quedo en espera de su respuesta.', externalUrl: 'https://www.youtube.com/watch?v=AZJnFJTRCGU' },
  { courseId: 2, sortOrder: 3, title: 'Gramática Intermedia: Condicionales', description: 'Aprende a usar los condicionales para expresar situaciones hipotéticas.', content: '## Condicional Zero (hechos generales)\n\n**Estructura:** If + present simple, present simple\n- If you heat water to 100°C, it boils.\n\n## Primer Condicional (situaciones posibles)\n\n**Estructura:** If + present simple, will + verb\n- If I finish early, I will call you.\n- If the client pays, we will ship the order.\n\n## Segundo Condicional (situaciones hipotéticas)\n\n**Estructura:** If + past simple, would + verb\n- If I had more time, I would learn more English.\n- If she were the manager, she would change the policy.\n\n### Ejercicios prácticos\n1. Complete: "If I _____ (have) a car, I _____ (drive) to work."\n2. Complete: "If it _____ (rain) tomorrow, we _____ (cancel) the event."', externalUrl: 'https://www.youtube.com/watch?v=If7QJTBf4xI' },

  // ─── INGLÉS AVANZADO (id=3) ───────────────────────────────────────────────
  { courseId: 3, sortOrder: 1, title: 'Inglés para Presentaciones Ejecutivas', description: 'Aprende a estructurar y presentar ideas complejas en inglés ante audiencias ejecutivas.', content: '## Estructura de una Presentación Ejecutiva\n\n**Apertura impactante:**\n- "Good morning everyone. Today I\'d like to talk about..."\n- "I\'m going to present our Q3 results and outline our strategy for..."\n\n**Transiciones fluidas:**\n- "Moving on to our next point..."\n- "As you can see from this chart..."\n- "This brings me to my next point..."\n\n**Manejo de preguntas:**\n- "That\'s an excellent question. Let me address that by..."\n- "I\'ll come back to that in a moment."\n- "Could you clarify what you mean by...?"\n\n**Cierre poderoso:**\n- "To summarize the key takeaways..."\n- "I\'d like to leave you with this thought..."\n- "Thank you for your time and attention."', externalUrl: 'https://www.youtube.com/watch?v=V8eLdbKXGzk' },
  { courseId: 3, sortOrder: 2, title: 'Escritura Profesional Avanzada', description: 'Redacta propuestas, informes y comunicaciones ejecutivas en inglés impecable.', content: '## Tipos de Documentos Profesionales\n\n### Propuestas de Negocio\n**Estructura:**\n1. Executive Summary\n2. Problem Statement\n3. Proposed Solution\n4. Timeline & Milestones\n5. Budget\n6. Conclusion\n\n### Informes Ejecutivos\n- Use **active voice**: "The team completed the project" (not "The project was completed by the team")\n- Be **concise**: avoid filler words like "basically", "actually", "very"\n- Use **data**: "Revenue increased by 23%" instead of "Revenue increased significantly"\n\n### Emails Ejecutivos\n**Subject line:** Clear and specific\n- ✅ "Q3 Sales Report - Action Required by Friday"\n- ❌ "Important information"\n\n**Body structure:**\n1. Purpose (1 sentence)\n2. Context (2-3 sentences)\n3. Action required (bullet points)\n4. Deadline\n5. Professional closing', externalUrl: 'https://www.youtube.com/watch?v=bE7fMnqMHFk' },

  // ─── EXCEL (id=4) ─────────────────────────────────────────────────────────
  { courseId: 4, sortOrder: 1, title: 'Introducción a Excel: Interfaz y Navegación', description: 'Conoce la interfaz de Excel, cómo navegar entre hojas y las funciones básicas.', content: '## ¿Qué es Microsoft Excel?\n\nExcel es una hoja de cálculo que permite organizar datos, hacer cálculos y crear gráficas.\n\n## Partes de la Interfaz\n\n- **Barra de herramientas (Ribbon):** Contiene todas las funciones organizadas en pestañas\n- **Barra de fórmulas:** Muestra el contenido de la celda seleccionada\n- **Celda:** La intersección de una fila y columna (ej: A1, B3)\n- **Hoja de cálculo:** La cuadrícula donde ingresas datos\n- **Pestañas de hojas:** En la parte inferior, para navegar entre hojas\n\n## Atajos de Teclado Esenciales\n\n| Atajo | Función |\n|-------|--------|\n| Ctrl+C | Copiar |\n| Ctrl+V | Pegar |\n| Ctrl+Z | Deshacer |\n| Ctrl+S | Guardar |\n| Ctrl+F | Buscar |\n| Ctrl+Home | Ir a celda A1 |\n| F2 | Editar celda |\n\n## Tipos de Datos\n- **Texto:** Nombres, descripciones\n- **Números:** Cantidades, precios\n- **Fechas:** Fechas y horas\n- **Fórmulas:** Cálculos automáticos (empiezan con =)', externalUrl: 'https://www.youtube.com/watch?v=rwbho0CgEAI' },
  { courseId: 4, sortOrder: 2, title: 'Fórmulas Esenciales: SUMA, PROMEDIO, SI', description: 'Aprende las fórmulas más usadas en el trabajo diario con Excel.', content: '## Fórmulas Básicas\n\n### SUMA\n```\n=SUMA(A1:A10)    → Suma del rango A1 a A10\n=SUMA(A1,B1,C1)  → Suma de celdas específicas\n```\n\n### PROMEDIO\n```\n=PROMEDIO(A1:A10) → Promedio del rango\n```\n\n### MAX y MIN\n```\n=MAX(A1:A10) → Valor máximo\n=MIN(A1:A10) → Valor mínimo\n```\n\n### CONTAR\n```\n=CONTAR(A1:A10)   → Cuenta celdas con números\n=CONTARA(A1:A10)  → Cuenta celdas no vacías\n```\n\n## Función SI (IF)\n```\n=SI(condición, valor_si_verdadero, valor_si_falso)\n\nEjemplo:\n=SI(B2>=60, "Aprobado", "Reprobado")\n=SI(C2>1000, "Bono", "Sin bono")\n```\n\n## BUSCARV (VLOOKUP)\n```\n=BUSCARV(valor_buscado, rango, columna, 0)\n\nEjemplo: Buscar el precio de un producto por su código\n=BUSCARV(A2, $D$2:$E$100, 2, 0)\n```', externalUrl: 'https://www.youtube.com/watch?v=Jl0Qk63z2ZY' },
  { courseId: 4, sortOrder: 3, title: 'Tablas Dinámicas y Gráficas', description: 'Crea reportes automáticos con tablas dinámicas y visualiza datos con gráficas.', content: '## Tablas Dinámicas (Pivot Tables)\n\nLas tablas dinámicas permiten resumir y analizar grandes cantidades de datos en segundos.\n\n### Cómo crear una tabla dinámica:\n1. Selecciona tus datos (incluyendo encabezados)\n2. Ve a **Insertar → Tabla dinámica**\n3. Elige dónde colocarla (hoja nueva o existente)\n4. Arrastra campos a las áreas:\n   - **Filas:** Categorías a analizar\n   - **Columnas:** Comparaciones\n   - **Valores:** Qué calcular (suma, promedio, conteo)\n   - **Filtros:** Para filtrar datos\n\n### Ejemplo práctico:\nSi tienes ventas por vendedor y mes:\n- Filas: Vendedor\n- Columnas: Mes\n- Valores: Suma de ventas\n\n## Gráficas\n\n1. Selecciona los datos a graficar\n2. Ve a **Insertar → Gráficos**\n3. Elige el tipo:\n   - **Barras/Columnas:** Comparar cantidades\n   - **Líneas:** Mostrar tendencias en el tiempo\n   - **Pastel:** Mostrar proporciones\n   - **Dispersión:** Relación entre variables', externalUrl: 'https://www.youtube.com/watch?v=qu-AK0Hv0b4' },

  // ─── WORD Y POWERPOINT (id=5) ─────────────────────────────────────────────
  { courseId: 5, sortOrder: 1, title: 'Word: Documentos Profesionales', description: 'Crea documentos formales con formato profesional en Microsoft Word.', content: '## Formato Básico en Word\n\n### Estilos de Texto\n- **Negrita:** Ctrl+B\n- *Cursiva:* Ctrl+I\n- Subrayado: Ctrl+U\n\n### Estilos de Párrafo\nUsa los **Estilos predefinidos** (Título 1, Título 2, Normal) para mantener consistencia.\n\n## Estructura de un Documento Profesional\n\n1. **Encabezado:** Logo de la empresa, nombre, fecha\n2. **Título del documento**\n3. **Cuerpo:** Organizado con títulos y subtítulos\n4. **Pie de página:** Número de página, confidencialidad\n\n## Herramientas Útiles\n\n- **Tabla de contenido automática:** Referencias → Tabla de contenido\n- **Corrector ortográfico:** F7\n- **Control de cambios:** Revisar → Control de cambios\n- **Combinar correspondencia:** Para cartas masivas personalizadas\n\n## Atajos Esenciales\n\n| Atajo | Función |\n|-------|--------|\n| Ctrl+Enter | Salto de página |\n| Ctrl+Shift+N | Estilo Normal |\n| Alt+Shift+D | Insertar fecha |\n| Ctrl+K | Insertar hipervínculo |', externalUrl: 'https://www.youtube.com/watch?v=S-nHYzK-BVg' },
  { courseId: 5, sortOrder: 2, title: 'PowerPoint: Presentaciones Impactantes', description: 'Diseña presentaciones visuales y profesionales que comuniquen con claridad.', content: '## Principios de una Buena Presentación\n\n### Regla 10-20-30\n- **10 diapositivas** máximo\n- **20 minutos** de duración\n- **30 puntos** de tamaño de fuente mínimo\n\n### Regla de los 6x6\n- Máximo **6 viñetas** por diapositiva\n- Máximo **6 palabras** por viñeta\n\n## Estructura Recomendada\n\n1. **Portada:** Título, subtítulo, fecha, logo\n2. **Agenda:** Qué se verá en la presentación\n3. **Contenido:** Máximo 7-8 diapositivas\n4. **Conclusiones:** Puntos clave\n5. **Preguntas:** Diapositiva de cierre\n\n## Diseño Visual\n\n- Usa **máximo 2-3 colores** por presentación\n- Imágenes de alta calidad (usa Unsplash o Pexels gratis)\n- Evita fondos con mucho texto\n- Usa **iconos** en lugar de texto cuando sea posible\n\n## Animaciones\n- Usa animaciones **sutiles** (Aparecer, Desvanecer)\n- Evita animaciones que distraigan (Rebote, Giro)\n- Las transiciones entre diapositivas: usa "Desvanecer" o ninguna', externalUrl: 'https://www.youtube.com/watch?v=_WnhoIbfcoM' },

  // ─── PRIMEROS AUXILIOS (id=6) ─────────────────────────────────────────────
  { courseId: 6, sortOrder: 1, title: 'Principios Básicos de Primeros Auxilios', description: 'Aprende los principios fundamentales y cómo actuar en una emergencia.', content: '## ¿Qué son los Primeros Auxilios?\n\nSon las medidas de atención inmediata que se dan a una persona que ha sufrido un accidente o enfermedad repentina, **antes de que llegue ayuda médica profesional**.\n\n## La Cadena de Supervivencia\n\n1. **Reconocer** la emergencia y llamar al 911\n2. **RCP temprana** (Reanimación Cardiopulmonar)\n3. **Desfibrilación temprana** (si hay DEA disponible)\n4. **Atención médica avanzada**\n\n## Protocolo PAS\n\n- **P**roteger: Asegura la escena (¿hay peligro?)\n- **A**visar: Llama al 911 o pide a alguien que llame\n- **S**ocorrer: Brinda los primeros auxilios\n\n## Reglas de Oro\n\n✅ Mantén la calma\n✅ No muevas a la víctima (a menos que haya peligro)\n✅ No des medicamentos sin prescripción\n✅ Habla con la víctima para tranquilizarla\n✅ Espera a los servicios de emergencia\n\n⚠️ **Número de emergencias en México: 911**', externalUrl: 'https://www.youtube.com/watch?v=cosVnFMTRlQ' },
  { courseId: 6, sortOrder: 2, title: 'RCP: Reanimación Cardiopulmonar', description: 'Aprende a realizar RCP correctamente para salvar una vida.', content: '## ¿Cuándo Aplicar RCP?\n\nCuando la persona:\n- No responde a estímulos\n- No respira o respira de forma anormal\n- No tiene pulso\n\n## Pasos del RCP (Adultos)\n\n### 1. Verifica la seguridad del lugar\n### 2. Verifica la respuesta\nSacude suavemente los hombros: "¿Estás bien?"\n\n### 3. Llama al 911\nO pide a alguien que llame mientras tú inicias el RCP.\n\n### 4. Posición de las manos\n- Coloca el talón de una mano en el **centro del pecho** (sobre el esternón)\n- Pon la otra mano encima\n- Entrelaza los dedos\n\n### 5. Compresiones\n- **Profundidad:** 5-6 cm\n- **Ritmo:** 100-120 compresiones por minuto\n- **Cuenta:** 30 compresiones\n\n### 6. Ventilaciones de rescate\n- Inclina la cabeza hacia atrás\n- 2 ventilaciones de 1 segundo cada una\n\n### 7. Repite\n- Ciclos de 30 compresiones + 2 ventilaciones\n- Continúa hasta que llegue ayuda o la persona responda\n\n> 💡 **Tip:** El ritmo de 100-120/min es similar a la canción "Stayin\' Alive" de Bee Gees', externalUrl: 'https://www.youtube.com/watch?v=hizBdM1Ob68' },
  { courseId: 6, sortOrder: 3, title: 'Heridas, Quemaduras y Fracturas', description: 'Cómo atender correctamente heridas, quemaduras y posibles fracturas.', content: '## Heridas\n\n### Heridas Leves\n1. Lava tus manos\n2. Limpia la herida con agua y jabón\n3. Aplica antiséptico (agua oxigenada o yodo)\n4. Cubre con gasa estéril y cinta adhesiva\n\n### Heridas con Hemorragia\n1. Aplica **presión directa** con tela limpia\n2. Mantén la presión por **10-15 minutos**\n3. Eleva la extremidad afectada\n4. No retires la tela si se empapa, agrega más encima\n\n## Quemaduras\n\n### Quemadura Leve (1er grado)\n- Enrojecimiento de la piel\n- **Tratamiento:** Agua fría corriente por 10-20 minutos\n- ❌ NO uses hielo, mantequilla ni pasta de dientes\n\n### Quemadura Grave (2do/3er grado)\n- Ampollas, piel carbonizada\n- **Tratamiento:** Llama al 911, cubre con tela limpia húmeda\n\n## Fracturas\n\n**Señales:** Dolor intenso, deformidad, incapacidad de mover la extremidad\n\n1. **No muevas** la extremidad afectada\n2. **Inmoviliza** con una férula improvisada (tabla, revista)\n3. Aplica hielo envuelto en tela\n4. Lleva al médico', externalUrl: 'https://www.youtube.com/watch?v=CE0bHMGsNkY' },

  // ─── TÉCNICAS DE VENTAS (id=7) ────────────────────────────────────────────
  { courseId: 7, sortOrder: 1, title: 'Psicología del Cliente y el Proceso de Compra', description: 'Entiende cómo piensan los clientes y qué los motiva a comprar.', content: '## ¿Por Qué Compra la Gente?\n\nLas personas compran por **emociones** y justifican con **lógica**.\n\n## Las 4 Motivaciones de Compra\n\n1. **Ganancia:** Quieren ganar dinero, tiempo o recursos\n2. **Ahorro:** Quieren ahorrar dinero, tiempo o esfuerzo\n3. **Seguridad:** Quieren protegerse a sí mismos y a su familia\n4. **Estatus:** Quieren sentirse importantes o reconocidos\n\n## El Proceso de Decisión de Compra\n\n1. **Reconocimiento del problema:** "Necesito esto"\n2. **Búsqueda de información:** Investiga opciones\n3. **Evaluación de alternativas:** Compara opciones\n4. **Decisión de compra:** Elige\n5. **Comportamiento post-compra:** ¿Está satisfecho?\n\n## Tipos de Clientes\n\n| Tipo | Característica | Cómo venderle |\n|------|---------------|---------------|\n| Analítico | Quiere datos y pruebas | Presenta estadísticas |\n| Expresivo | Emocional, social | Cuenta historias |\n| Conductor | Directo, quiere resultados | Ve al grano |\n| Amistoso | Busca relaciones | Construye confianza |', externalUrl: 'https://www.youtube.com/watch?v=MzPFvFDGCNs' },
  { courseId: 7, sortOrder: 2, title: 'Técnicas de Cierre de Ventas', description: 'Aprende las técnicas más efectivas para cerrar ventas con confianza.', content: '## El Momento del Cierre\n\nEl cierre no es el final de la venta, es la consecuencia natural de un buen proceso.\n\n## Señales de Compra\n\n✅ Hace preguntas sobre el producto/servicio\n✅ Pregunta por precios, formas de pago o plazos\n✅ Pide referencias o casos de éxito\n✅ Asiente con la cabeza frecuentemente\n✅ Calcula cuánto necesitaría\n\n## Técnicas de Cierre\n\n### 1. Cierre Directo\n> "¿Empezamos hoy?"\n> "¿Lo procesamos ahora?"\n\n### 2. Cierre por Alternativa\n> "¿Prefiere el plan mensual o el anual?"\n> "¿Quiere que se lo enviemos el martes o el jueves?"\n\n### 3. Cierre por Urgencia\n> "Esta promoción termina el viernes"\n> "Solo quedan 3 disponibles"\n\n### 4. Cierre por Resumen\n> "Entonces acordamos que usted recibirá X, Y y Z por el precio de $..., ¿correcto?"\n\n### 5. Cierre por Prueba\n> "¿Qué le parecería probarlo por 30 días sin compromiso?"\n\n## Manejo de Objeciones\n\n- "Es muy caro" → "¿Caro comparado con qué?"\n- "Lo voy a pensar" → "¿Qué necesita para decidirse hoy?"\n- "No tengo tiempo" → "¿Cuándo sería un buen momento?"', externalUrl: 'https://www.youtube.com/watch?v=PHHkFBnhXZY' },

  // ─── CÓMO GANAR AMIGOS (id=8) ─────────────────────────────────────────────
  { courseId: 8, sortOrder: 1, title: 'Principios Fundamentales para Tratar con Personas', description: 'Los principios básicos de Dale Carnegie para relacionarte mejor con los demás.', content: '## "Cómo Ganar Amigos e Influir en las Personas" - Dale Carnegie\n\nEste libro, publicado en 1936, sigue siendo uno de los más vendidos de todos los tiempos en desarrollo personal y relaciones humanas.\n\n## Principios Fundamentales\n\n### 1. No critiques, no condenes, no te quejes\n> "La crítica es inútil porque pone a la persona a la defensiva y generalmente la hace esforzarse por justificarse."\n\n**Aplicación práctica:** Antes de criticar a alguien, pregúntate: ¿Qué gano con esto? ¿Hay una forma mejor de comunicarlo?\n\n### 2. Demuestra aprecio honesto y sincero\n> "El principio más profundo de la naturaleza humana es el anhelo de ser apreciado."\n\n**Aplicación práctica:** Cada día, encuentra algo genuino que apreciar en alguien de tu equipo y díselo.\n\n### 3. Despierta en los demás un deseo vehemente\n> "La única forma de influir en alguien es hablar de lo que él quiere y mostrarle cómo conseguirlo."\n\n**Aplicación práctica:** Antes de pedir algo, piensa: ¿Cómo beneficia esto a la otra persona?', externalUrl: 'https://www.youtube.com/watch?v=6MBm8-4J0Ys' },
  { courseId: 8, sortOrder: 2, title: 'Cómo Hacer que la Gente te Aprecie', description: 'Técnicas para crear conexiones genuinas y ser una persona magnética.', content: '## Seis Maneras de Agradar a los Demás\n\n### 1. Interésate genuinamente en los demás\n> "Puedes ganar más amigos en dos meses interesándote en los demás que en dos años tratando de que los demás se interesen en ti."\n\n**Práctica:** Recuerda el nombre, cumpleaños y detalles importantes de las personas.\n\n### 2. Sonríe\n> "Una sonrisa no cuesta nada pero crea mucho."\n\n### 3. Recuerda que el nombre de una persona es el sonido más dulce\n> Usa el nombre de la persona en la conversación (sin exagerar).\n\n### 4. Sé un buen oyente\n> "Para ser interesante, sé interesado."\n\n**Práctica:** En tu próxima conversación, haz preguntas y escucha el 70% del tiempo.\n\n### 5. Habla en términos de los intereses del otro\n> Antes de hablar de ti, pregunta sobre los intereses de la otra persona.\n\n### 6. Haz que la otra persona se sienta importante\n> Hazlo de manera sincera y genuina.', externalUrl: 'https://www.youtube.com/watch?v=6MBm8-4J0Ys' },

  // ─── LIDERAZGO DE PERSONAL (id=9) ─────────────────────────────────────────
  { courseId: 9, sortOrder: 1, title: 'Estilos de Liderazgo y Cuándo Usarlos', description: 'Conoce los diferentes estilos de liderazgo y cómo adaptarlos a tu equipo.', content: '## Los 4 Estilos de Liderazgo\n\n### 1. Liderazgo Directivo\n- **Cuándo usarlo:** Con empleados nuevos o en crisis\n- **Cómo:** Das instrucciones claras y supervisas de cerca\n- **Frase típica:** "Haz esto de esta manera"\n\n### 2. Liderazgo Coach\n- **Cuándo usarlo:** Con empleados con potencial pero poca confianza\n- **Cómo:** Explicas el porqué, haces preguntas, das retroalimentación\n- **Frase típica:** "¿Qué crees que deberías hacer en esta situación?"\n\n### 3. Liderazgo Participativo\n- **Cuándo usarlo:** Con empleados competentes que necesitan motivación\n- **Cómo:** Involucras al equipo en las decisiones\n- **Frase típica:** "¿Qué opinan del plan?"\n\n### 4. Liderazgo Delegador\n- **Cuándo usarlo:** Con empleados altamente competentes y motivados\n- **Cómo:** Asignas responsabilidad total\n- **Frase típica:** "Tú decides cómo hacerlo"\n\n## El Error Más Común\n\nUsar siempre el mismo estilo con todos. Un buen líder **adapta su estilo** según la persona y la situación.', externalUrl: 'https://www.youtube.com/watch?v=TIhMmudMnBY' },
  { courseId: 9, sortOrder: 2, title: 'Comunicación Efectiva con tu Equipo', description: 'Aprende a dar retroalimentación, resolver conflictos y motivar a tu equipo.', content: '## Cómo Dar Retroalimentación Efectiva\n\n### El Modelo SBI (Situación-Comportamiento-Impacto)\n\n1. **Situación:** "En la reunión de ayer con el cliente..."\n2. **Comportamiento:** "...llegaste 15 minutos tarde..."\n3. **Impacto:** "...lo cual generó una mala impresión y tuvimos que repetir la presentación."\n\n**Importante:** Habla del comportamiento, no de la persona.\n- ❌ "Eres irresponsable"\n- ✅ "Llegaste tarde a la reunión"\n\n## Cómo Resolver Conflictos\n\n1. **Escucha ambas partes** por separado primero\n2. **Identifica el problema real** (no los síntomas)\n3. **Busca intereses comunes** entre las partes\n4. **Genera opciones** de solución juntos\n5. **Acuerda un plan** con compromisos específicos\n\n## Motivación del Equipo\n\n**Teoría de Herzberg:**\n- **Factores de higiene** (evitan insatisfacción): salario justo, condiciones de trabajo, seguridad\n- **Factores motivadores** (generan satisfacción): reconocimiento, responsabilidad, crecimiento\n\n> 💡 El dinero evita la insatisfacción pero no motiva a largo plazo. El reconocimiento y el crecimiento sí.', externalUrl: 'https://www.youtube.com/watch?v=ReRcHdeUG9Y' },

  // ─── MANEJO DEL ESTRÉS (id=10) ────────────────────────────────────────────
  { courseId: 10, sortOrder: 1, title: 'Entendiendo el Estrés Laboral', description: 'Qué es el estrés, cómo te afecta y cuáles son sus causas más comunes en el trabajo.', content: '## ¿Qué es el Estrés?\n\nEl estrés es la respuesta de tu cuerpo ante una demanda o amenaza percibida. En pequeñas dosis es útil (te mantiene alerta), pero el estrés crónico es dañino.\n\n## Síntomas del Estrés\n\n**Físicos:** Dolor de cabeza, tensión muscular, fatiga, problemas digestivos, insomnio\n\n**Emocionales:** Ansiedad, irritabilidad, tristeza, dificultad para concentrarse\n\n**Conductuales:** Comer en exceso o muy poco, aislamiento, procrastinación\n\n## Causas Más Comunes en el Trabajo\n\n1. **Sobrecarga de trabajo:** Más tareas de las que puedes manejar\n2. **Falta de control:** No tener autonomía sobre tu trabajo\n3. **Conflictos interpersonales:** Problemas con jefes o compañeros\n4. **Inseguridad laboral:** Miedo a perder el trabajo\n5. **Falta de reconocimiento:** Sentir que tu trabajo no vale\n6. **Mala comunicación:** No saber qué se espera de ti\n\n## El Ciclo del Estrés\n\nEstrés → Tensión → Agotamiento → Burnout\n\n> 🚨 El **burnout** es el agotamiento total (físico, emocional y mental) por estrés crónico. Requiere atención profesional.', externalUrl: 'https://www.youtube.com/watch?v=hnpQrMqDoqE' },
  { courseId: 10, sortOrder: 2, title: 'Técnicas de Manejo del Estrés', description: 'Herramientas prácticas para reducir el estrés y mejorar tu bienestar en el trabajo.', content: '## Técnicas Inmediatas (para el momento)\n\n### Respiración 4-7-8\n1. Inhala por la nariz contando **4 segundos**\n2. Mantén el aire contando **7 segundos**\n3. Exhala por la boca contando **8 segundos**\n4. Repite 4 veces\n\n### Técnica 5-4-3-2-1 (Grounding)\nCuando sientas ansiedad, identifica:\n- **5 cosas** que puedes ver\n- **4 cosas** que puedes tocar\n- **3 cosas** que puedes escuchar\n- **2 cosas** que puedes oler\n- **1 cosa** que puedes saborear\n\n## Técnicas a Largo Plazo\n\n### Gestión del Tiempo\n- **Técnica Pomodoro:** 25 min de trabajo + 5 min de descanso\n- **Matriz de Eisenhower:** Clasifica tareas por urgencia e importancia\n- **Regla de los 2 minutos:** Si tarda menos de 2 min, hazlo ahora\n\n### Hábitos Saludables\n- Duerme 7-8 horas\n- Ejercicio 30 min al día (reduce cortisol)\n- Limita cafeína y alcohol\n- Desconéctate del trabajo fuera de horario\n\n### Mindfulness\n- 10 minutos de meditación al día\n- Aplicaciones recomendadas: Headspace, Calm, Insight Timer (gratis)', externalUrl: 'https://www.youtube.com/watch?v=0fL-pn80s-c' },

  // ─── HÁBITOS PARA EL ÉXITO (id=11) ───────────────────────────────────────
  { courseId: 11, sortOrder: 1, title: 'Los 7 Hábitos de la Gente Altamente Efectiva', description: 'Resumen y aplicación práctica del libro de Stephen Covey.', content: '## "Los 7 Hábitos de la Gente Altamente Efectiva" - Stephen Covey\n\n## Los 7 Hábitos\n\n### Hábito 1: Ser Proactivo\n> "No soy el producto de mis circunstancias, soy el producto de mis decisiones."\n\n**Aplicación:** Enfócate en tu **círculo de influencia** (lo que puedes controlar), no en tu círculo de preocupación.\n\n### Hábito 2: Empezar con el Fin en Mente\n> Visualiza claramente a dónde quieres llegar antes de empezar.\n\n**Aplicación:** Escribe tu misión personal. ¿Qué quieres que digan de ti cuando te jubiles?\n\n### Hábito 3: Poner Primero lo Primero\n> Prioriza lo importante sobre lo urgente.\n\n**La Matriz de Eisenhower:**\n| | Urgente | No Urgente |\n|--|---------|------------|\n| **Importante** | Crisis (hazlo ya) | Planificación (prioridad) |\n| **No Importante** | Interrupciones (delega) | Trivialidades (elimina) |\n\n### Hábito 4: Pensar en Ganar-Ganar\n> Busca acuerdos donde todos se beneficien.\n\n### Hábito 5: Busca Primero Entender, Luego Ser Entendido\n> Escucha para entender, no para responder.\n\n### Hábito 6: Sinergizar\n> El todo es mayor que la suma de sus partes.\n\n### Hábito 7: Afilar la Sierra\n> Renuévate constantemente: físico, mental, social, espiritual.', externalUrl: 'https://www.youtube.com/watch?v=ktlTxC4QG8g' },

  // ─── EL PODER DEL AHORA (id=12) ───────────────────────────────────────────
  { courseId: 12, sortOrder: 1, title: 'Vivir en el Presente: Conceptos Clave', description: 'Resumen y aplicación práctica de "El Poder del Ahora" de Eckhart Tolle.', content: '## "El Poder del Ahora" - Eckhart Tolle\n\n## Concepto Central\n\n> "El momento presente es lo único que siempre existirá. El pasado es un recuerdo y el futuro es una proyección mental. Solo el AHORA es real."\n\n## Ideas Principales\n\n### 1. La Mente como Obstáculo\nLa mayoría de nuestro sufrimiento viene de pensar demasiado en el pasado (culpa, arrepentimiento) o en el futuro (ansiedad, preocupación).\n\n**Práctica:** Cuando notes que tu mente se va al pasado o futuro, pregúntate: "¿Qué está pasando AHORA mismo?"\n\n### 2. El Observador\nHay una diferencia entre **tú** y **tus pensamientos**. Puedes observar tus pensamientos sin identificarte con ellos.\n\n**Práctica:** Siéntate en silencio 5 minutos. Observa tus pensamientos como si fueran nubes pasando. No los juzgues, solo obsérvalos.\n\n### 3. El Dolor del Ego\nEl ego vive en el pasado y el futuro. Necesita problemas para existir. La paz está en el presente.\n\n### 4. Aceptación\n> "Acepta lo que es. Deja ir lo que fue. Ten fe en lo que será."\n\n**Práctica diaria:** Cada mañana, antes de revisar el teléfono, toma 3 respiraciones profundas y observa cómo te sientes en este momento.', externalUrl: 'https://www.youtube.com/watch?v=e-T8SHMbmkY' },

  // ─── NUTRICIÓN (id=13) ────────────────────────────────────────────────────
  { courseId: 13, sortOrder: 1, title: 'Fundamentos de una Alimentación Saludable', description: 'Aprende los principios básicos de la nutrición para mejorar tu energía y salud.', content: '## Los Macronutrientes\n\n### 1. Carbohidratos (55-65% de tu dieta)\n**Función:** Energía principal del cuerpo y cerebro\n\n**Buenos carbohidratos:** Avena, arroz integral, papa, frutas, verduras\n**Evitar:** Pan blanco, azúcar, refrescos, frituras\n\n### 2. Proteínas (15-25% de tu dieta)\n**Función:** Construir y reparar tejidos, músculos, enzimas\n\n**Fuentes:** Pollo, pescado, huevo, frijoles, lentejas, queso cottage\n**Necesitas:** ~0.8g por kg de peso corporal al día\n\n### 3. Grasas (20-35% de tu dieta)\n**Función:** Hormonas, absorción de vitaminas, energía\n\n**Grasas buenas:** Aguacate, aceite de oliva, nueces, pescado\n**Evitar:** Grasas trans (comida procesada, margarina)\n\n## El Plato del Bien Comer\n\n- **½ plato:** Verduras y frutas\n- **¼ plato:** Cereales y tubérculos (preferir integrales)\n- **¼ plato:** Leguminosas y alimentos de origen animal\n\n## Hidratación\n\n- Bebe **2 litros de agua** al día mínimo\n- El 75% de la fatiga es causada por deshidratación leve\n- Señal: orina de color amarillo claro = bien hidratado', externalUrl: 'https://www.youtube.com/watch?v=fqhYBTg73fw' },
  { courseId: 13, sortOrder: 2, title: 'Alimentación Saludable en el Trabajo', description: 'Estrategias prácticas para comer bien aunque tengas poco tiempo.', content: '## El Problema del Trabajo\n\nCuando estamos ocupados tendemos a:\n- Saltarnos comidas\n- Comer comida rápida o chatarra\n- Comer frente a la pantalla (sin atención)\n- Tomar mucho café y poco agua\n\n## Estrategias Prácticas\n\n### Meal Prep (Preparación de comida)\nDedica 1-2 horas el domingo para preparar:\n- Verduras cortadas\n- Proteína cocida (pollo, huevo duro)\n- Granos cocidos (arroz, frijoles)\n\n### Snacks Saludables para la Oficina\n- Nueces y almendras (puñado pequeño)\n- Fruta fresca (manzana, plátano)\n- Yogur natural\n- Zanahoria con hummus\n- Barras de proteína (sin azúcar añadida)\n\n### Cómo Pedir Comida Saludable\n- Pide ensalada en lugar de papas fritas\n- Elige agua en lugar de refresco\n- Pide aderezos aparte\n- Evita los tamaños "extra grande"\n\n### El Desayuno es Clave\n> "Desayuna como rey, come como príncipe, cena como mendigo"\n\n**Desayuno ideal:** Proteína + carbohidrato complejo + fruta\nEjemplo: Huevo + avena + plátano', externalUrl: 'https://www.youtube.com/watch?v=fqhYBTg73fw' },

  // ─── EJERCICIO (id=14) ────────────────────────────────────────────────────
  { courseId: 14, sortOrder: 1, title: 'Beneficios del Ejercicio y Cómo Empezar', description: 'Por qué el ejercicio es esencial y cómo crear un hábito sostenible.', content: '## Beneficios del Ejercicio Regular\n\n**Físicos:**\n- Reduce riesgo de enfermedades cardíacas, diabetes tipo 2 y cáncer\n- Mantiene peso saludable\n- Fortalece huesos y músculos\n- Mejora la calidad del sueño\n\n**Mentales:**\n- Reduce estrés, ansiedad y depresión\n- Mejora la concentración y memoria\n- Aumenta la energía\n- Libera endorfinas (hormona de la felicidad)\n\n**Laborales:**\n- Empleados que hacen ejercicio son 15% más productivos\n- Menos días de enfermedad\n- Mejor manejo del estrés\n\n## Recomendaciones de la OMS\n\n- **Adultos:** 150-300 min de actividad moderada por semana\n- O 75-150 min de actividad intensa\n- + Ejercicios de fuerza 2 días por semana\n\n## Cómo Crear el Hábito\n\n1. **Empieza pequeño:** 10-15 minutos al día\n2. **Misma hora:** Crea una rutina (mañana o noche)\n3. **Hazlo fácil:** Ropa lista la noche anterior\n4. **Registra tu progreso:** App o cuaderno\n5. **Encuentra algo que disfrutes:** Caminar, bailar, nadar, ciclismo', externalUrl: 'https://www.youtube.com/watch?v=DsVzKCk065g' },
  { courseId: 14, sortOrder: 2, title: 'Ejercicios que Puedes Hacer en la Oficina', description: 'Rutinas de ejercicio de 10-15 minutos que puedes hacer en tu lugar de trabajo.', content: '## El Problema del Sedentarismo\n\nEstar sentado más de 8 horas al día aumenta el riesgo de:\n- Enfermedades cardiovasculares\n- Diabetes tipo 2\n- Dolor de espalda y cuello\n- Obesidad\n\n> 💡 Levántate y muévete por lo menos **1 vez cada hora**\n\n## Ejercicios en tu Escritorio (sin equipo)\n\n### Estiramiento de Cuello (2 min)\n1. Inclina la cabeza hacia la derecha, mantén 15 seg\n2. Inclina hacia la izquierda, mantén 15 seg\n3. Gira suavemente de lado a lado\n\n### Estiramiento de Espalda (2 min)\n1. Siéntate derecho, entrelaza los dedos y estira los brazos hacia adelante\n2. Gira el torso hacia la derecha, luego izquierda\n\n### Ejercicios de Pie (5 min)\n1. **Sentadillas:** 15 repeticiones\n2. **Elevación de talones:** 20 repeticiones\n3. **Marcha en lugar:** 1 minuto\n\n## Rutina de 10 Minutos en Descanso\n\n1. Caminata rápida (3 min)\n2. Sentadillas (2 min)\n3. Lagartijas contra la pared (2 min)\n4. Estiramiento general (3 min)\n\n## Apps Recomendadas (Gratis)\n- **7 Minute Workout:** Rutinas rápidas\n- **Nike Training Club:** Rutinas para todos los niveles\n- **FitOn:** Clases en video gratis', externalUrl: 'https://www.youtube.com/watch?v=IODxDxX7oi4' },

  // ─── SALUD MENTAL (id=15) ─────────────────────────────────────────────────
  { courseId: 15, sortOrder: 1, title: 'Salud Mental: Qué Es y Por Qué Importa', description: 'Entiende qué es la salud mental, cómo cuidarla y cuándo buscar ayuda.', content: '## ¿Qué es la Salud Mental?\n\nLa salud mental incluye nuestro **bienestar emocional, psicológico y social**. Afecta cómo pensamos, sentimos y actuamos.\n\n## Mitos vs. Realidades\n\n| Mito | Realidad |\n|------|----------|\n| "Los problemas mentales son debilidad" | Son enfermedades como cualquier otra |\n| "Solo afecta a personas con trauma" | Puede afectar a cualquiera |\n| "Hay que aguantarse" | Buscar ayuda es fortaleza, no debilidad |\n| "La medicación es mala" | A veces es necesaria y salva vidas |\n\n## Señales de Alerta\n\n🚨 Busca ayuda profesional si experimentas:\n- Tristeza o vacío que dura más de 2 semanas\n- Ansiedad que interfiere con tu vida diaria\n- Pensamientos de hacerte daño\n- Cambios drásticos en sueño o apetito\n- Dificultad para funcionar en el trabajo\n\n## Recursos de Ayuda en México\n\n- **SAPTEL (24/7):** 55 5259-8121\n- **IMSS:** Consulta con médico de familia\n- **UNAM (gratis):** Clínica de Salud Mental\n- **Línea de la Vida:** 800 911 2000\n\n> 💚 Cuidar tu salud mental es tan importante como cuidar tu salud física.', externalUrl: 'https://www.youtube.com/watch?v=DxIDKZHW3-E' },
  { courseId: 15, sortOrder: 2, title: 'Inteligencia Emocional en el Trabajo', description: 'Desarrolla tu inteligencia emocional para mejorar tus relaciones y desempeño laboral.', content: '## ¿Qué es la Inteligencia Emocional (IE)?\n\nDaniel Goleman define la IE como la capacidad de **reconocer, entender y gestionar** nuestras emociones y las de los demás.\n\n## Los 5 Componentes de la IE\n\n### 1. Autoconciencia\n> Conocer tus propias emociones y cómo afectan tu comportamiento.\n\n**Práctica:** Lleva un diario emocional. Anota cómo te sentiste cada día y por qué.\n\n### 2. Autorregulación\n> Controlar tus impulsos y emociones negativas.\n\n**Práctica:** Antes de reaccionar con enojo, cuenta hasta 10 y respira.\n\n### 3. Motivación\n> Trabajar por razones más allá del dinero o el estatus.\n\n**Práctica:** Conecta tu trabajo con un propósito mayor.\n\n### 4. Empatía\n> Entender y compartir los sentimientos de los demás.\n\n**Práctica:** Antes de juzgar a alguien, pregúntate: "¿Qué estará viviendo esta persona?"\n\n### 5. Habilidades Sociales\n> Gestionar relaciones y construir redes.\n\n**Práctica:** Practica la escucha activa: no interrumpas, haz preguntas, resume lo que escuchaste.\n\n## IE vs. IQ\n\n> Estudios de Harvard muestran que el **80% del éxito profesional** se debe a la inteligencia emocional, y solo el 20% al coeficiente intelectual.', externalUrl: 'https://www.youtube.com/watch?v=Y7m9eNoB3NU' },
];

// Insertar todos los módulos
let inserted = 0;
for (const mod of modules) {
  await conn.query(
    'INSERT INTO course_modules (courseId, title, description, content, externalUrl, sortOrder) VALUES (?, ?, ?, ?, ?, ?)',
    [mod.courseId, mod.title, mod.description, mod.content, mod.externalUrl, mod.sortOrder]
  );
  inserted++;
}

console.log(`✅ Insertados ${inserted} módulos en ${new Set(modules.map(m => m.courseId)).size} cursos.`);
await conn.end();
